[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fabric"
version = "0.0.1"
requires-python = ">= 3.11"

[project.scripts]
bar = "fabric:main"

[tool.setuptools]
packages = ["fabric"]

[tool.setuptools.package-data]
bar = ["fabric.css"]
