name: "Build configurations and upload cache to Cachix"
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: cachix/install-nix-action@v25
              with:
                  nix_path: nixpkgs=channel:nixos-unstable

            - uses: cachix/cachix-action@v14
              with:
                  name: calops
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

            - uses: DeterminateSystems/magic-nix-cache-action@v2

            - run: nix build .#nixosConfigurations.cachix.config.system.build.toplevel
            - run: nix build .#darwinConfigurations.cachix.config.system.build.toplevel
