name: "Build configurations"
on:
    workflow_dispatch:
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - uses: cachix/cachix-action@v15
              with:
                  name: calops
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - uses: DeterminateSystems/magic-nix-cache-action@v7
            - run: nix build .#homeConfigurations.cachix@cachix-linux.activationPackage

    build-darwin:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - uses: cachix/cachix-action@v15
              with:
                  name: calops
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - uses: DeterminateSystems/magic-nix-cache-action@v7
            - run: nix build .#homeConfigurations.cachix@cachix-darwin.activationPackage
